{{- define "webhooks.secret" }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: "{{ .app_name }}"
  name: "{{ .app_name }}"
stringData:
  WEBHOOK_SECRET: {{ randAlphaNum 10 | quote }}
{{- end }}