name: Pelorus Exporter Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - samples/
      - charts/
      - demo/
      - docs/
      - labs/
      - tests/
      - storage/
      - chart_schema.yaml
      - CONTRIBUTING.md

jobs:
  build-committime:
    runs-on: ubuntu-20.04 # recommended https://github.com/marketplace/actions/push-to-registry#note-about-github-runners-and-podman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        uses: redhat-actions/s2i-build@v1
        with:
          path_context: 'exporters'
          builder_image: 'registry.access.redhat.com/ubi8/python-38'
          image_name: 'committime-exporter'
          image_tag: ${{ github.sha }}

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: 'committime-exporter'
          tags: ${{ github.sha }} latest
          registry: quay.io/pelorus
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
  build-deploytime:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        uses: redhat-actions/s2i-build@v1
        with:
          path_context: 'exporters'
          builder_image: 'registry.access.redhat.com/ubi8/python-38'
          image_name: 'deploytime-exporter'
          image_tag: ${{ github.sha }}

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: 'deploytime-exporter'
          tags: ${{ github.sha }} latest
          registry: quay.io/pelorus
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
  build-failure:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2i and Build container image
      - name: Setup and Build
        uses: redhat-actions/s2i-build@v1
        with:
          path_context: 'exporters'
          builder_image: 'registry.access.redhat.com/ubi8/python-38'
          image_name: 'failure-exporter'
          image_tag: ${{ github.sha }}

      # Push Image to Quay registry
      - name: Push To Quay Action
        uses: redhat-actions/push-to-registry@v2
        with:
          image: 'failure-exporter'
          tags: ${{ github.sha }} latest
          registry: quay.io/pelorus
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
