name: Chart Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart testing
        uses: helm/chart-testing-action@v2.0.1
        with:
          version: 3.5.2

      - name: Run chart lint
        run: ct lint
